variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
  - .cache/pip

stages:
- quality
- tests
- deploy

.install-deps-template: &install-deps
  before_script:
  - pip install pdm
  - pdm --version
  - pdm install

# Quality jobs

.quality-template: &quality
  <<: *install-deps
  image: python:3.6
  stage: quality

check-docs:
  <<: *quality
  script: pdm run duty check-docs

check-code-quality:
  <<: *quality
  script: pdm run duty check-code-quality

check-types:
  <<: *quality
  script: pdm run duty check-types

check-dependencies:
  <<: *quality
  script: pdm run duty check-dependencies

# Tests jobs

.test-template: &test
  <<: *install-deps
  stage: tests
  script: pdm run duty test
  artifacts:
    paths:
    - .coverage-*

python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8

python3.9:
  <<: *test
  image: python:3.9


pages:
  stage: deploy
  <<: *install-deps
  image: python:3.6
  dependencies:
  - python3.6
  - python3.7
  - python3.8
  - python3.9
  script:
  - pdm run duty coverage
  - pdm run duty docs
  coverage: '/^TOTAL.+?(\d+\.\d+\%)$/'
  artifacts:
    paths:
    - public
  only:
  - master
